[2023-10-09T02:32:49.447+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:27:43.657034+00:00 [queued]>
[2023-10-09T02:32:49.459+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:27:43.657034+00:00 [queued]>
[2023-10-09T02:32:49.459+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-09T02:32:49.482+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-09 02:27:43.657034+00:00
[2023-10-09T02:32:49.488+0000] {standard_task_runner.py:57} INFO - Started process 499 to run task
[2023-10-09T02:32:49.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-09T02:27:43.657034+00:00', '--job-id', '641', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpk9h7ava8']
[2023-10-09T02:32:49.493+0000] {standard_task_runner.py:85} INFO - Job 641: Subtask upload_to_s3
[2023-10-09T02:32:49.551+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:27:43.657034+00:00 [running]> on host e12c8be37a23
[2023-10-09T02:32:49.655+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T02:27:43.657034+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T02:27:43.657034+00:00'
[2023-10-09T02:32:49.657+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-09T02:32:49.657+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231009']
[2023-10-09T02:32:49.672+0000] {subprocess.py:86} INFO - Output:
[2023-10-09T02:32:49.767+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-09T02:32:49.770+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-09T02:32:49.783+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-09T02:32:49.788+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231009T022743, start_date=20231009T023249, end_date=20231009T023249
[2023-10-09T02:32:49.813+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 641 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 499)
[2023-10-09T02:32:49.825+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-09T02:32:49.846+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
