[2023-10-23T22:02:01.553+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T21:17:47.994524+00:00 [queued]>
[2023-10-23T22:02:01.571+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T21:17:47.994524+00:00 [queued]>
[2023-10-23T22:02:01.572+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-23T22:02:01.603+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-23 21:17:47.994524+00:00
[2023-10-23T22:02:01.611+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2023-10-23T22:02:01.617+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-23T21:17:47.994524+00:00', '--job-id', '892', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpmc6nmfn_']
[2023-10-23T22:02:01.619+0000] {standard_task_runner.py:85} INFO - Job 892: Subtask upload_to_s3
[2023-10-23T22:02:01.805+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T21:17:47.994524+00:00 [running]> on host 4be7b32a0cc0
[2023-10-23T22:02:01.962+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T21:17:47.994524+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T21:17:47.994524+00:00'
[2023-10-23T22:02:01.964+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-23T22:02:01.966+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/upload_aws_s3.py 20231023']
[2023-10-23T22:02:01.983+0000] {subprocess.py:86} INFO - Output:
[2023-10-23T22:02:05.573+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-23T22:02:05.574+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 73, in <module>
[2023-10-23T22:02:05.577+0000] {subprocess.py:93} INFO -     main()
[2023-10-23T22:02:05.579+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 36, in main
[2023-10-23T22:02:05.583+0000] {subprocess.py:93} INFO -     upload_file_to_s3(conn)
[2023-10-23T22:02:05.584+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 68, in upload_file_to_s3
[2023-10-23T22:02:05.585+0000] {subprocess.py:93} INFO -     Filename="/tmp/" + FILENAME, Bucket=BUCKET_NAME, Key=KEY
[2023-10-23T22:02:05.586+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
[2023-10-23T22:02:05.587+0000] {subprocess.py:93} INFO -     callback=Callback,
[2023-10-23T22:02:05.588+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
[2023-10-23T22:02:05.589+0000] {subprocess.py:93} INFO -     future.result()
[2023-10-23T22:02:05.591+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
[2023-10-23T22:02:05.592+0000] {subprocess.py:93} INFO -     return self._coordinator.result()
[2023-10-23T22:02:05.593+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
[2023-10-23T22:02:05.593+0000] {subprocess.py:93} INFO -     raise self._exception
[2023-10-23T22:02:05.594+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
[2023-10-23T22:02:05.595+0000] {subprocess.py:93} INFO -     self._submit(transfer_future=transfer_future, **kwargs)
[2023-10-23T22:02:05.596+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 585, in _submit
[2023-10-23T22:02:05.597+0000] {subprocess.py:93} INFO -     upload_input_manager.provide_transfer_size(transfer_future)
[2023-10-23T22:02:05.598+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
[2023-10-23T22:02:05.599+0000] {subprocess.py:93} INFO -     self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
[2023-10-23T22:02:05.599+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/utils.py", line 247, in get_file_size
[2023-10-23T22:02:05.600+0000] {subprocess.py:93} INFO -     return os.path.getsize(filename)
[2023-10-23T22:02:05.601+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/genericpath.py", line 50, in getsize
[2023-10-23T22:02:05.601+0000] {subprocess.py:93} INFO -     return os.stat(filename).st_size
[2023-10-23T22:02:05.602+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/20231023.csv'
[2023-10-23T22:02:05.686+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-23T22:02:05.708+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-23T22:02:05.714+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231023T211747, start_date=20231023T220201, end_date=20231023T220205
[2023-10-23T22:02:05.759+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 892 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 66)
[2023-10-23T22:02:05.774+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-23T22:02:05.803+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
