[2023-10-23T19:11:46.232+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T19:10:52.103168+00:00 [queued]>
[2023-10-23T19:11:46.242+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T19:10:52.103168+00:00 [queued]>
[2023-10-23T19:11:46.243+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-23T19:11:46.261+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-23 19:10:52.103168+00:00
[2023-10-23T19:11:46.266+0000] {standard_task_runner.py:57} INFO - Started process 1246 to run task
[2023-10-23T19:11:46.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-23T19:10:52.103168+00:00', '--job-id', '807', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmptgbfa5_f']
[2023-10-23T19:11:46.272+0000] {standard_task_runner.py:85} INFO - Job 807: Subtask upload_to_s3
[2023-10-23T19:11:46.327+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-23T19:10:52.103168+00:00 [running]> on host 18e533bd1f06
[2023-10-23T19:11:46.468+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T19:10:52.103168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T19:10:52.103168+00:00'
[2023-10-23T19:11:46.470+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-23T19:11:46.471+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/upload_aws_s3.py 20231023']
[2023-10-23T19:11:46.484+0000] {subprocess.py:86} INFO - Output:
[2023-10-23T19:12:00.179+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-23T19:12:00.179+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
[2023-10-23T19:12:00.182+0000] {subprocess.py:93} INFO -     future.result()
[2023-10-23T19:12:00.183+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
[2023-10-23T19:12:00.183+0000] {subprocess.py:93} INFO -     return self._coordinator.result()
[2023-10-23T19:12:00.184+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
[2023-10-23T19:12:00.185+0000] {subprocess.py:93} INFO -     raise self._exception
[2023-10-23T19:12:00.186+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
[2023-10-23T19:12:00.186+0000] {subprocess.py:93} INFO -     return self._execute_main(kwargs)
[2023-10-23T19:12:00.187+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
[2023-10-23T19:12:00.188+0000] {subprocess.py:93} INFO -     return_value = self._main(**kwargs)
[2023-10-23T19:12:00.188+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 758, in _main
[2023-10-23T19:12:00.189+0000] {subprocess.py:93} INFO -     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
[2023-10-23T19:12:00.189+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
[2023-10-23T19:12:00.190+0000] {subprocess.py:93} INFO -     return self._make_api_call(operation_name, kwargs)
[2023-10-23T19:12:00.191+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 964, in _make_api_call
[2023-10-23T19:12:00.192+0000] {subprocess.py:93} INFO -     raise error_class(parsed_response, operation_name)
[2023-10-23T19:12:00.194+0000] {subprocess.py:93} INFO - botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-10-23T19:12:00.195+0000] {subprocess.py:93} INFO - 
[2023-10-23T19:12:00.196+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-23T19:12:00.197+0000] {subprocess.py:93} INFO - 
[2023-10-23T19:12:00.197+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-23T19:12:00.198+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 73, in <module>
[2023-10-23T19:12:00.199+0000] {subprocess.py:93} INFO -     main()
[2023-10-23T19:12:00.200+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 36, in main
[2023-10-23T19:12:00.201+0000] {subprocess.py:93} INFO -     upload_file_to_s3(conn)
[2023-10-23T19:12:00.202+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 68, in upload_file_to_s3
[2023-10-23T19:12:00.203+0000] {subprocess.py:93} INFO -     Filename="/tmp/" + FILENAME, Bucket=BUCKET_NAME, Key=KEY
[2023-10-23T19:12:00.203+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
[2023-10-23T19:12:00.204+0000] {subprocess.py:93} INFO -     callback=Callback,
[2023-10-23T19:12:00.205+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 300, in upload_file
[2023-10-23T19:12:00.206+0000] {subprocess.py:93} INFO -     filename, '/'.join([bucket, key]), e
[2023-10-23T19:12:00.207+0000] {subprocess.py:93} INFO - boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/20231023.csv to jobdata-bucket/20231023.csv: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-10-23T19:12:00.285+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-23T19:12:00.302+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-23T19:12:00.306+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231023T191052, start_date=20231023T191146, end_date=20231023T191200
[2023-10-23T19:12:00.331+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 807 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 1246)
[2023-10-23T19:12:00.376+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-23T19:12:00.396+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
