[2023-11-02T21:31:04.464+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.upload_to_s3 manual__2023-11-02T21:24:07.308877+00:00 [queued]>
[2023-11-02T21:31:04.477+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.upload_to_s3 manual__2023-11-02T21:24:07.308877+00:00 [queued]>
[2023-11-02T21:31:04.477+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-11-02T21:31:04.529+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-11-02 21:24:07.308877+00:00
[2023-11-02T21:31:04.550+0000] {standard_task_runner.py:57} INFO - Started process 1178 to run task
[2023-11-02T21:31:04.560+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Google_Job_Listings_Data_Pipeline', 'upload_to_s3', 'manual__2023-11-02T21:24:07.308877+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpm0oo4o4f']
[2023-11-02T21:31:04.562+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask upload_to_s3
[2023-11-02T21:31:04.629+0000] {task_command.py:410} INFO - Running <TaskInstance: Google_Job_Listings_Data_Pipeline.upload_to_s3 manual__2023-11-02T21:24:07.308877+00:00 [running]> on host 1f525f761703
[2023-11-02T21:31:04.722+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Google_Job_Listings_Data_Pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T21:24:07.308877+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T21:24:07.308877+00:00'
[2023-11-02T21:31:04.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-02T21:31:04.725+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/upload_aws_s3.py 20231102']
[2023-11-02T21:31:04.740+0000] {subprocess.py:86} INFO - Output:
[2023-11-02T21:31:07.205+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-02T21:31:07.205+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
[2023-11-02T21:31:07.206+0000] {subprocess.py:93} INFO -     future.result()
[2023-11-02T21:31:07.206+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
[2023-11-02T21:31:07.207+0000] {subprocess.py:93} INFO -     return self._coordinator.result()
[2023-11-02T21:31:07.208+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
[2023-11-02T21:31:07.209+0000] {subprocess.py:93} INFO -     raise self._exception
[2023-11-02T21:31:07.209+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
[2023-11-02T21:31:07.210+0000] {subprocess.py:93} INFO -     return self._execute_main(kwargs)
[2023-11-02T21:31:07.211+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
[2023-11-02T21:31:07.211+0000] {subprocess.py:93} INFO -     return_value = self._main(**kwargs)
[2023-11-02T21:31:07.212+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 758, in _main
[2023-11-02T21:31:07.212+0000] {subprocess.py:93} INFO -     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
[2023-11-02T21:31:07.213+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
[2023-11-02T21:31:07.213+0000] {subprocess.py:93} INFO -     return self._make_api_call(operation_name, kwargs)
[2023-11-02T21:31:07.214+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 964, in _make_api_call
[2023-11-02T21:31:07.214+0000] {subprocess.py:93} INFO -     raise error_class(parsed_response, operation_name)
[2023-11-02T21:31:07.215+0000] {subprocess.py:93} INFO - botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-11-02T21:31:07.215+0000] {subprocess.py:93} INFO - 
[2023-11-02T21:31:07.216+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-11-02T21:31:07.216+0000] {subprocess.py:93} INFO - 
[2023-11-02T21:31:07.217+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-02T21:31:07.217+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 73, in <module>
[2023-11-02T21:31:07.218+0000] {subprocess.py:93} INFO -     main()
[2023-11-02T21:31:07.219+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 36, in main
[2023-11-02T21:31:07.220+0000] {subprocess.py:93} INFO -     upload_file_to_s3(conn)
[2023-11-02T21:31:07.221+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 68, in upload_file_to_s3
[2023-11-02T21:31:07.221+0000] {subprocess.py:93} INFO -     Filename="/tmp/" + FILENAME, Bucket=BUCKET_NAME, Key=KEY
[2023-11-02T21:31:07.222+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
[2023-11-02T21:31:07.223+0000] {subprocess.py:93} INFO -     callback=Callback,
[2023-11-02T21:31:07.223+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 300, in upload_file
[2023-11-02T21:31:07.224+0000] {subprocess.py:93} INFO -     filename, '/'.join([bucket, key]), e
[2023-11-02T21:31:07.224+0000] {subprocess.py:93} INFO - boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/20231102.csv to jobdata-bucket/20231102.csv: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-11-02T21:31:07.299+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-02T21:31:07.315+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-02T21:31:07.320+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Google_Job_Listings_Data_Pipeline, task_id=upload_to_s3, execution_date=20231102T212407, start_date=20231102T213104, end_date=20231102T213107
[2023-11-02T21:31:07.337+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 75 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 1178)
[2023-11-02T21:31:07.385+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-02T21:31:07.407+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
