[2023-10-23T21:05:56.399+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-23T20:54:34.471480+00:00 [queued]>
[2023-10-23T21:05:56.413+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-23T20:54:34.471480+00:00 [queued]>
[2023-10-23T21:05:56.413+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-23T21:05:56.455+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): run_script_in_docker> on 2023-10-23 20:54:34.471480+00:00
[2023-10-23T21:05:56.463+0000] {standard_task_runner.py:57} INFO - Started process 88 to run task
[2023-10-23T21:05:56.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'run_script_in_docker', 'manual__2023-10-23T20:54:34.471480+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpk1_0g58r']
[2023-10-23T21:05:56.469+0000] {standard_task_runner.py:85} INFO - Job 818: Subtask run_script_in_docker
[2023-10-23T21:05:56.585+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-23T20:54:34.471480+00:00 [running]> on host 4be7b32a0cc0
[2023-10-23T21:05:56.729+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='run_script_in_docker' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T20:54:34.471480+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T20:54:34.471480+00:00'
[2023-10-23T21:05:56.814+0000] {docker.py:334} INFO - Starting docker container from image webscrape-container
[2023-10-23T21:05:56.840+0000] {docker.py:343} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-10-23T21:06:00.208+0000] {docker.py:403} INFO - [13:60:1023/210600.207587:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-23T21:06:00.746+0000] {docker.py:403} INFO - [13:63:1023/210600.745527:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-23T21:06:00.747+0000] {docker.py:403} INFO - [13:63:1023/210600.745738:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-23T21:06:00.763+0000] {docker.py:403} INFO - [13:60:1023/210600.762149:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-23T21:06:00.764+0000] {docker.py:403} INFO - [13:60:1023/210600.762753:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-23T21:06:00.764+0000] {docker.py:403} INFO - [13:60:1023/210600.762817:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:60:1023/210600.762829:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-23T21:06:00.885+0000] {docker.py:403} INFO - [13:60:1023/210600.883130:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:60:1023/210600.883211:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-23T21:06:01.039+0000] {docker.py:403} INFO - DevTools listening on ws://127.0.0.1:4444/devtools/browser/ff79aa4d-9a65-4de9-afaa-e90c6a374bc9
[2023-10-23T21:06:01.171+0000] {docker.py:403} INFO - [13:13:1023/210601.168373:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type:
[2023-10-23T21:06:01.280+0000] {docker.py:403} INFO - [13:108:1023/210601.273024:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:108:1023/210601.273106:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:108:1023/210601.273195:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:108:1023/210601.273244:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:108:1023/210601.273288:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-23T21:06:01.435+0000] {docker.py:403} INFO - [70:70:1023/210601.433320:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[2023-10-23T21:06:01.837+0000] {docker.py:403} INFO - [136:136:1023/210601.835750:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[2023-10-23T21:08:30.591+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Extract_job_data_in_selenium_container, task_id=run_script_in_docker, execution_date=20231023T205434, start_date=20231023T210556, end_date=20231023T210830
[2023-10-23T21:08:30.656+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-23T21:08:30.724+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
