[2023-10-21T21:00:14.481+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-21T20:59:21.894457+00:00 [queued]>
[2023-10-21T21:00:14.493+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-21T20:59:21.894457+00:00 [queued]>
[2023-10-21T21:00:14.493+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-21T21:00:14.512+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-21 20:59:21.894457+00:00
[2023-10-21T21:00:14.517+0000] {standard_task_runner.py:57} INFO - Started process 5283 to run task
[2023-10-21T21:00:14.521+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-21T20:59:21.894457+00:00', '--job-id', '791', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpnc42hija']
[2023-10-21T21:00:14.523+0000] {standard_task_runner.py:85} INFO - Job 791: Subtask upload_to_s3
[2023-10-21T21:00:14.580+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-21T20:59:21.894457+00:00 [running]> on host 18e533bd1f06
[2023-10-21T21:00:14.674+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T20:59:21.894457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T20:59:21.894457+00:00'
[2023-10-21T21:00:14.676+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-21T21:00:14.677+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/upload_aws_s3.py 20231021']
[2023-10-21T21:00:14.690+0000] {subprocess.py:86} INFO - Output:
[2023-10-21T21:00:18.245+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-21T21:00:18.246+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
[2023-10-21T21:00:18.250+0000] {subprocess.py:93} INFO -     future.result()
[2023-10-21T21:00:18.252+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
[2023-10-21T21:00:18.256+0000] {subprocess.py:93} INFO -     return self._coordinator.result()
[2023-10-21T21:00:18.257+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
[2023-10-21T21:00:18.259+0000] {subprocess.py:93} INFO -     raise self._exception
[2023-10-21T21:00:18.260+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
[2023-10-21T21:00:18.261+0000] {subprocess.py:93} INFO -     return self._execute_main(kwargs)
[2023-10-21T21:00:18.263+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
[2023-10-21T21:00:18.264+0000] {subprocess.py:93} INFO -     return_value = self._main(**kwargs)
[2023-10-21T21:00:18.265+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 758, in _main
[2023-10-21T21:00:18.266+0000] {subprocess.py:93} INFO -     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
[2023-10-21T21:00:18.268+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
[2023-10-21T21:00:18.268+0000] {subprocess.py:93} INFO -     return self._make_api_call(operation_name, kwargs)
[2023-10-21T21:00:18.271+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/botocore/client.py", line 964, in _make_api_call
[2023-10-21T21:00:18.272+0000] {subprocess.py:93} INFO -     raise error_class(parsed_response, operation_name)
[2023-10-21T21:00:18.273+0000] {subprocess.py:93} INFO - botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-10-21T21:00:18.274+0000] {subprocess.py:93} INFO - 
[2023-10-21T21:00:18.274+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-21T21:00:18.275+0000] {subprocess.py:93} INFO - 
[2023-10-21T21:00:18.275+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-21T21:00:18.276+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 73, in <module>
[2023-10-21T21:00:18.277+0000] {subprocess.py:93} INFO -     main()
[2023-10-21T21:00:18.277+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 36, in main
[2023-10-21T21:00:18.278+0000] {subprocess.py:93} INFO -     upload_file_to_s3(conn)
[2023-10-21T21:00:18.278+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 68, in upload_file_to_s3
[2023-10-21T21:00:18.279+0000] {subprocess.py:93} INFO -     Filename="/tmp/" + FILENAME, Bucket=BUCKET_NAME, Key=KEY
[2023-10-21T21:00:18.279+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
[2023-10-21T21:00:18.279+0000] {subprocess.py:93} INFO -     callback=Callback,
[2023-10-21T21:00:18.280+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 300, in upload_file
[2023-10-21T21:00:18.280+0000] {subprocess.py:93} INFO -     filename, '/'.join([bucket, key]), e
[2023-10-21T21:00:18.281+0000] {subprocess.py:93} INFO - boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/20231021.csv to jobdata-bucket/20231021.csv: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
[2023-10-21T21:00:18.370+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-21T21:00:18.393+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-21T21:00:18.400+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231021T205921, start_date=20231021T210014, end_date=20231021T210018
[2023-10-21T21:00:18.421+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 791 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 5283)
[2023-10-21T21:00:18.440+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-21T21:00:18.464+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
