[2023-10-08T21:15:33.926+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-08T21:15:32.641125+00:00 [queued]>
[2023-10-08T21:15:33.942+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-08T21:15:32.641125+00:00 [queued]>
[2023-10-08T21:15:33.942+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-08T21:15:33.966+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): run_script_in_docker> on 2023-10-08 21:15:32.641125+00:00
[2023-10-08T21:15:33.975+0000] {standard_task_runner.py:57} INFO - Started process 357 to run task
[2023-10-08T21:15:33.981+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'run_script_in_docker', 'manual__2023-10-08T21:15:32.641125+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpab6i9ikh']
[2023-10-08T21:15:33.983+0000] {standard_task_runner.py:85} INFO - Job 509: Subtask run_script_in_docker
[2023-10-08T21:15:34.053+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-08T21:15:32.641125+00:00 [running]> on host cae9180efd34
[2023-10-08T21:15:34.208+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='run_script_in_docker' AIRFLOW_CTX_EXECUTION_DATE='2023-10-08T21:15:32.641125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-08T21:15:32.641125+00:00'
[2023-10-08T21:15:34.242+0000] {docker.py:462} INFO - Pulling docker image ***-webscrape-container-1
[2023-10-08T21:15:36.966+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=***-webscrape-container-1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 464, in execute
    for output in self.cli.pull(self.image, stream=True, decode=True):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=airflow-webscrape-container-1: Not Found ("pull access denied for airflow-webscrape-container-1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
[2023-10-08T21:15:37.010+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=run_script_in_docker, execution_date=20231008T211532, start_date=20231008T211533, end_date=20231008T211537
[2023-10-08T21:15:37.060+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 509 for task run_script_in_docker (404 Client Error for http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=airflow-webscrape-container-1: Not Found ("pull access denied for airflow-webscrape-container-1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"); 357)
[2023-10-08T21:15:37.098+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-08T21:15:37.118+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
