[2023-10-09T02:15:48.793+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-09T02:15:46.478647+00:00 [queued]>
[2023-10-09T02:15:48.811+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-09T02:15:46.478647+00:00 [queued]>
[2023-10-09T02:15:48.812+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-09T02:15:48.838+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): run_script_in_docker> on 2023-10-09 02:15:46.478647+00:00
[2023-10-09T02:15:48.845+0000] {standard_task_runner.py:57} INFO - Started process 134 to run task
[2023-10-09T02:15:48.849+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'run_script_in_docker', 'manual__2023-10-09T02:15:46.478647+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpkr74aynl']
[2023-10-09T02:15:48.851+0000] {standard_task_runner.py:85} INFO - Job 613: Subtask run_script_in_docker
[2023-10-09T02:15:48.932+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.run_script_in_docker manual__2023-10-09T02:15:46.478647+00:00 [running]> on host e12c8be37a23
[2023-10-09T02:15:49.095+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='run_script_in_docker' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T02:15:46.478647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T02:15:46.478647+00:00'
[2023-10-09T02:15:49.132+0000] {docker.py:334} INFO - Starting docker container from image webscrape-container
[2023-10-09T02:15:49.145+0000] {docker.py:343} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-10-09T02:15:51.551+0000] {docker.py:403} INFO - [13:64:1009/021551.550369:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.552+0000] {docker.py:403} INFO - [13:64:1009/021551.550845:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.556+0000] {docker.py:403} INFO - [13:59:1009/021551.555056:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:59:1009/021551.555106:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:59:1009/021551.555128:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:59:1009/021551.555136:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:59:1009/021551.555143:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-09T02:15:51.582+0000] {docker.py:403} INFO - [13:59:1009/021551.581086:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-09T02:15:51.582+0000] {docker.py:403} INFO - [13:59:1009/021551.581433:ERROR:bus.cc(406)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2023-10-09T02:15:51.615+0000] {docker.py:403} INFO - DevTools listening on ws://127.0.0.1:4444/devtools/browser/26d40047-4b39-40f6-aec8-39b9a023e8b2
[2023-10-09T02:15:51.653+0000] {docker.py:403} INFO - [13:13:1009/021551.651958:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type:
[2023-10-09T02:15:51.678+0000] {docker.py:403} INFO - [13:103:1009/021551.677277:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[13:103:1009/021551.677414:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.679+0000] {docker.py:403} INFO - [13:103:1009/021551.677510:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.680+0000] {docker.py:403} INFO - [13:103:1009/021551.677606:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.682+0000] {docker.py:403} INFO - [13:103:1009/021551.677654:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2023-10-09T02:15:51.917+0000] {docker.py:403} INFO - [74:74:1009/021551.915935:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[2023-10-09T02:16:26.810+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Extract_job_data_in_selenium_container, task_id=run_script_in_docker, execution_date=20231009T021546, start_date=20231009T021548, end_date=20231009T021626
[2023-10-09T02:16:26.884+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-09T02:16:26.934+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
